/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SocialMediaPostService } from "../socialMediaPost.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SocialMediaPostCreateInput } from "./SocialMediaPostCreateInput";
import { SocialMediaPost } from "./SocialMediaPost";
import { SocialMediaPostFindManyArgs } from "./SocialMediaPostFindManyArgs";
import { SocialMediaPostWhereUniqueInput } from "./SocialMediaPostWhereUniqueInput";
import { SocialMediaPostUpdateInput } from "./SocialMediaPostUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SocialMediaPostControllerBase {
  constructor(
    protected readonly service: SocialMediaPostService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SocialMediaPost })
  @nestAccessControl.UseRoles({
    resource: "SocialMediaPost",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSocialMediaPost(
    @common.Body() data: SocialMediaPostCreateInput
  ): Promise<SocialMediaPost> {
    return await this.service.createSocialMediaPost({
      data: {
        ...data,

        event: data.event
          ? {
              connect: data.event,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SocialMediaPost] })
  @ApiNestedQuery(SocialMediaPostFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SocialMediaPost",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async socialMediaPosts(
    @common.Req() request: Request
  ): Promise<SocialMediaPost[]> {
    const args = plainToClass(SocialMediaPostFindManyArgs, request.query);
    return this.service.socialMediaPosts({
      ...args,
      select: {
        content: true,
        createdAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SocialMediaPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SocialMediaPost",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async socialMediaPost(
    @common.Param() params: SocialMediaPostWhereUniqueInput
  ): Promise<SocialMediaPost | null> {
    const result = await this.service.socialMediaPost({
      where: params,
      select: {
        content: true,
        createdAt: true,

        event: {
          select: {
            id: true,
          },
        },

        id: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SocialMediaPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SocialMediaPost",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSocialMediaPost(
    @common.Param() params: SocialMediaPostWhereUniqueInput,
    @common.Body() data: SocialMediaPostUpdateInput
  ): Promise<SocialMediaPost | null> {
    try {
      return await this.service.updateSocialMediaPost({
        where: params,
        data: {
          ...data,

          event: data.event
            ? {
                connect: data.event,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SocialMediaPost })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SocialMediaPost",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSocialMediaPost(
    @common.Param() params: SocialMediaPostWhereUniqueInput
  ): Promise<SocialMediaPost | null> {
    try {
      return await this.service.deleteSocialMediaPost({
        where: params,
        select: {
          content: true,
          createdAt: true,

          event: {
            select: {
              id: true,
            },
          },

          id: true,
          timestamp: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
